import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
export const generatePDF = (
    transactions,
    summary,
    user
) => {
const doc=new jsPDF();
doc.setFontSize(24);
doc.setTextColor(37, 99, 235);
doc.text("FinanceOS", 14, 20);

doc.setFontSize(16);
doc.setTextColor(0, 0, 0);
doc.text("Financial Report", 14, 30);

doc.setDrawColor(37, 99, 235);
doc.line(14, 35, 196, 35);
doc.setFontSize(12);

doc.text(
  `User: ${user?.name || "Unknown"}`,
  14,
  48
);

doc.text(
  `Email: ${user?.email || "-"}`,
  14,
  56
);

doc.text(
  `Generated: ${new Date().toLocaleDateString(
    "en-IN"
  )}`,
  14,
  64
);
doc.setFontSize(15);
doc.text("Summary", 14, 80);

doc.setFontSize(12);

doc.text(
  `Total Income : ₹${summary.income.toLocaleString(
    "en-IN"
  )}`,
  20,
  92
);

doc.text(
  `Total Expense : ₹${summary.expense.toLocaleString(
    "en-IN"
  )}`,
  20,
  100
);

doc.text(
  `Net Balance : ₹${summary.balance.toLocaleString(
    "en-IN"
  )}`,
  20,
  108
);
const tableData = transactions.map((transaction) => [
  transaction.title,
  transaction.category,
  transaction.type,
  `${transaction.type === "income" ? "+" : "-"}₹${transaction.amount}`,
  new Date(transaction.date).toLocaleDateString("en-IN"),
]);
autoTable(doc, {
  startY: 120,

  head: [[
    "Title",
    "Category",
    "Type",
    "Amount",
    "Date",
  ]],

  body: tableData,

  headStyles: {
    fillColor: [37, 99, 235],
    textColor: [255, 255, 255],
    fontStyle: "bold",
  },

  alternateRowStyles: {
    fillColor: [245, 245, 245],
  },

  styles: {
    fontSize: 10,
    cellPadding: 3,
  },
});
const pageHeight = doc.internal.pageSize.height;

doc.setFontSize(10);

doc.setTextColor(120);

doc.text(
  "Generated by FinanceOS",
  14,
  pageHeight - 10
);
doc.save("FinanceOS_Report.pdf");
};