import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDF = (transactions, summary, user) => {
  const doc = new jsPDF();

  // ==========================
  // Colors
  // ==========================
  const primary = [37, 99, 235];
  const green = [34, 197, 94];
  const red = [239, 68, 68];
  const blue = [59, 130, 246];
  const dark = [30, 41, 59];
  const lightGray = [245, 245, 245];

  doc.setFont("helvetica", "normal");

  // ==========================
  // Header
  // ==========================
  doc.setFontSize(24);
  doc.setTextColor(...primary);
  doc.text("FinanceOS", 14, 20);

  doc.setFontSize(16);
  doc.setTextColor(...dark);
  doc.text("Financial Report", 14, 30);

  doc.setDrawColor(...primary);
  doc.setLineWidth(0.7);
  doc.line(14, 36, 196, 36);

  doc.setFontSize(12);

  doc.text(`User : ${user?.name || "Unknown"}`, 14, 48);
  doc.text(`Email : ${user?.email || "-"}`, 14, 56);

  doc.text(
    `Generated : ${new Date().toLocaleString("en-IN")}`,
    14,
    64
  );
  const reportId = `FIN-${Date.now()}`;

doc.text(
  `Report ID : ${reportId}`,
  14,
  72
);

doc.text(
  `Total Transactions : ${transactions.length}`,
  140,
  72
);

 
  doc.setFontSize(16);
  doc.setTextColor(...dark);
  doc.text("Financial Summary", 14, 82);

  const income = Number(summary?.income || 0);
  const expense = Number(summary?.expense || 0);
  const balance = Number(summary?.balance || 0);

  doc.setFillColor(...green);
  doc.roundedRect(14, 90, 56, 26, 3, 3, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.text("Total Income", 18, 100);

  doc.setFontSize(14);
  doc.text(
    `INR ${income.toLocaleString("en-IN")}`,
    18,
    110
  );

  doc.setFillColor(...red);
  doc.roundedRect(77, 90, 56, 26, 3, 3, "F");

  doc.setFontSize(11);
  doc.text("Total Expense", 81, 100);

  doc.setFontSize(14);
  doc.text(
    `INR ${expense.toLocaleString("en-IN")}`,
    81,
    110
  );

  doc.setFillColor(...blue);
  doc.roundedRect(140, 90, 56, 26, 3, 3, "F");

  doc.setFontSize(11);
  doc.text("Net Balance", 144, 100);

  doc.setFontSize(14);
  doc.text(
    `INR ${balance.toLocaleString("en-IN")}`,
    144,
    110
  );
  if (transactions.length === 0) {
  doc.setFontSize(13);
  doc.setTextColor(...dark);

  doc.text(
    "No transactions available for this report.",
    14,
    135
  );
} else {

const tableData = transactions.map((transaction) => [
    transaction.title,
    transaction.category,
    transaction.type,
    `${
      transaction.type === "income" ? "+" : "-"
    }INR ${Number(transaction.amount).toLocaleString("en-IN")}`,
    new Date(transaction.date).toLocaleDateString("en-IN"),
  ]);

  autoTable(doc, {

    startY: 128,

    head: [[
      "Title",
      "Category",
      "Type",
      "Amount",
      "Date",
    ]],

    body: tableData,

    theme: "striped",

    headStyles: {
      fillColor: primary,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      halign: "center",
      fontSize: 11,
    },

    bodyStyles: {
      fontSize: 10,
      textColor: dark,
    },

    alternateRowStyles: {
      fillColor: lightGray,
    },

    styles: {
      cellPadding: 4,
      overflow: "linebreak",
      valign: "middle",
    },

    columnStyles: {
      3: {
        halign: "right",
      },
      4: {
        halign: "center",
      },
    },
    didParseCell: function (data) {

  if (
    data.section === "body" &&
    data.column.index === 2
  ) {

    if (data.cell.raw === "income") {
      data.cell.styles.textColor = green;
      data.cell.styles.fontStyle = "bold";
    }

    if (data.cell.raw === "expense") {
      data.cell.styles.textColor = red;
      data.cell.styles.fontStyle = "bold";
    }

  }

},
  });
}
  const pages = doc.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    const pageHeight = doc.internal.pageSize.height;

    doc.setDrawColor(220);
    doc.line(
      14,
      pageHeight - 16,
      196,
      pageHeight - 16
    );

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
      "Generated by FinanceOS",
      14,
      pageHeight - 8
    );

    doc.text(
      `Page ${i} of ${pages}`,
      170,
      pageHeight - 8
    );
  }

  const fileName = `FinanceOS_Report_${
    new Date().toISOString().split("T")[0]
  }.pdf`;
doc.setProperties({
  title: "FinanceOS Financial Report",
  subject: "Expense Report",
  author: "FinanceOS",
  creator: "FinanceOS",
});
  doc.save(fileName);
};